# Coding Temple's Data Analytics Program  
---
# Advanced Python 1 - Intro to `numpy`
---



## Part 1: Working with `numpy`


### 1.1 Importing `numpy`

We've already used the `numpy` package by importing it and assigning it the standard alias of `np`. Do this again in the following cell - the more you practice typing these lines of code, the easier it will be to remember.

In [70]:
# Import numpy and assign it the standard alias
# YOUR CODE HERE
import numpy as np

### 1.1 Solution - Run this cell to check your answer in 1.1. Please do not edit the values in this cell!

In [ ]:
# DO NOT EDIT THIS CELL
assert np.__name__ == 'numpy', 'Make sure that you have properly imported numpy and aliased it as np!'

### 1.2 Generate random numbers

Create a `(5,3)` `numpy` array of random integer values between 0 and 100.

Use the the `random()` method in numpy to generate these integers. Name your new variable `myarray`. You should also print the array to check it's dimensions and values.

In [43]:
# Generate your random numbers
np.random.seed(1) #Seed generated for reproducibility
#YOUR CODE HERE
Matrix = np.zeros((5,3))
print(Matrix)
myarray = np.random.randint(0,10, size=(5,3))
print(myarray)
# Print out the array
#myarray

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[5 8 9]
 [5 0 0]
 [1 7 6]
 [9 2 4]
 [5 2 4]]


### 1.2 Solution - Run the following cell to check your answer.

In [ ]:
#DO NOT EDIT THIS CELL

#Verify the array was created with the correct name and has the proper shape
assert myarray.shape == (5,3), 'Make sure you create an array with the proper shape!'

### 1.3 Calculate BMI 

Using the two lists provided, please calculate the BMI(body mass index) of each individual using NDArrays. Save the variable containing your results as `bmi`

The formula for BMI in pounds and inches can be defined as: $BMI= \frac{703 * weight} {(height)^2}$

In [55]:

height = [55, 120, 90, 100]
weight = [170, 180, 190, 200]

# convert the lists to NumPy arrays
height_arr = np.array(height)
weight_arr = np.array(weight)

# calculate BMI using the formula
bmi = 703 * weight_arr / (height_arr ** 2)

print(bmi)



[39.50743802  8.7875     16.49012346 14.06      ]


### 1.3 Solution: Run the following cell to check your answer.

In [ ]:
# DO NOT EDIT THIS CELL
assert 'bmi' in dir() , 'Make sure you have saved your results to the proper variable name!'
assert type(bmi) == np.ndarray, 'Make sure that you made the calculation using an NDArray for both height and weight!'


### 1.4 Create a function 

Create a function named `my_func` that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [60]:
import numpy as np

def my_func(x,y)-> np.ndarray:
    matrix = np.random.random((x,y))
    return matrix

print(my_func(12,6))

[[0.94453072 0.98900143 0.00160942 0.82308195 0.69513326 0.15775758]
 [0.29509051 0.52315682 0.74039599 0.95740734 0.74004708 0.18006196]
 [0.28471028 0.80441816 0.97700184 0.37806787 0.50719113 0.28837784]
 [0.82709282 0.64662845 0.35366816 0.95869458 0.99726848 0.12568626]
 [0.37166976 0.78412811 0.6985289  0.59614044 0.644581   0.2798425 ]
 [0.38007635 0.29214736 0.04362149 0.73191967 0.31816132 0.58471854]
 [0.86512265 0.83784423 0.57266819 0.37606896 0.18977392 0.75842183]
 [0.83565824 0.1249339  0.55232586 0.26840293 0.04588576 0.60913238]
 [0.53158577 0.56129001 0.31218669 0.35374313 0.42252345 0.43496367]
 [0.64191623 0.08625351 0.89995819 0.25062213 0.74601627 0.67965633]
 [0.68154171 0.30482754 0.79732877 0.3658933  0.99510555 0.96833619]
 [0.70129584 0.65185643 0.56327413 0.23518719 0.96643994 0.72248391]]


### 1.5 Array practice

Time for some more practice. Run each of these tasks in the separate code cell listed below:

1.  Return the first row
2.  Return the last column
3.  Return the third column values from the 4th and 5th rows
4.  Multiply every value in the array by 2
5.  Divide every value by 3
6.  Increase the values in the first row by 12
7. Calculate the mean of the first column
8. Calculate the median of the array _after_ removing the 2 smallest values in the array
9. Calculate the standard deviation of the first 3 rows
10. Return values greater than 25 in the second column
11. Return values less than 40 in the array

In [62]:
# 1. Return the first row:
myarray = np.random.randint(100, size=(5, 3))
print(myarray[0])

[45 27 24]


In [63]:
# 2. Return the last column
print(myarray[:])

[[45 27 24]
 [34 46 58]
 [87 24 62]
 [ 9 16 64]
 [61 66 34]]


In [22]:
# 3. Return the third column values from the 4th and 5th rows
myarray[3:5,2]

array([37, 11])

In [21]:
# 4. Multiply every value in the array by 2
myarray * 2

array([[114, 100, 120],
       [ 36, 104, 100],
       [  0, 190, 194],
       [106, 122,  74],
       [162,  56,  22]])

In [71]:
# 5. Dividmye every value by 3
myarray / 3

array([[15.        ,  9.        ,  8.        ],
       [11.33333333, 15.33333333, 19.33333333],
       [29.        ,  8.        , 20.66666667],
       [ 3.        ,  5.33333333, 21.33333333],
       [20.33333333, 22.        , 11.33333333]])

In [27]:
# 6. Increase the values in the first row by 12
myarray[0] + 12

array([69, 62, 72])

In [96]:
# 7. Calculate the mean of the first column
myarray[:, 1:]
the_mean_arr = np.mean(myarray)
the_mean_arr

43.8

In [107]:
# 8. Calculate the median of the array after removing the 2 smallest values in the array
anarr = np.array([1, 2, 3, 45, 56])
anarr.sort()
anarr = anarr[2:]
arr_median = np.median(anarr)
arr_median

45.0

In [26]:
# 9. Calculate the standard deviation of the first 3 rows
# Generate a new array to work on
np.random.seed(2) # New seed for new array
np.std(myarray[0:3,:])

29.472313854711466

In [ ]:
# 10. Return values in the second column greater than 25
myarray[:,1] > 25

In [28]:
# 11. Return values < 40 in the array
myarray < 40

array([[False, False, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True,  True]])

### Solution 1.5: Run the following cell to view the solution for each of the above tasks.

A new array will be generated to demonstrate the solution - the values will not be the same as your array. But the code for each task will still apply.

In [ ]:
# DO NOT EDIT THIS CELL
# SOLUTION 1.5

# SOLUTION: Make sure you have completed all of the above tasks
# Generate your random numbers (NEW ARRAY)
myarray = np.random.randint(100, size=(5, 3))
print('The generated array: \n', myarray)
print('\n')

# 1. Return the first row:
print('1. The first row: ', myarray[0])
print('\n')

# 2. Return the last column
print('2. The last column: ', myarray[:,-1])
print('\n')

# 3. Return the third column values from the 4th and 5th rows
print('3. The 3rd column, 4th & 5th rows: ', myarray[3:5,2])
print('\n')

# 4. Multiply every value in the array by 2
# (operates on the original array)
print('4. Multiply by 2: \n', myarray * 2)
print('\n')

# 5. Divide every value by 3
# (operates on the original array)
print('5. Divide by 3: \n', myarray / 3)
print('\n')

# 6. Increase the values in the first row by 12
# (operates on the original array)
print('6. Add 12 to the first row: \n', myarray[0,:] + 12)
print('\n')

# 7. Calculate the mean of the first column
print('7. The mean of the 1st column: ', myarray[:,0].mean())
print('\n')

# 8. Calculate the median of the array after removing the 2 smallest values in the array
# flatten and sort (axis=None does the flattening)
myarray = np.sort(myarray, axis=None)
# remove two smallest values
myarray = myarray[2:]
# calculate the median
print('8. The median after removing the 2 smallest values: ', np.median(myarray))
print('\n')

# 9. Calculate the standard deviation of the first 3 rows
# Generate new array first:
myarray = np.random.randint(100, size=(5, 3))
# Then calculate the std:
print('9. The standard deviation is: ', np.std(myarray[0:3,:]))
print('\n')

# 10. Return values in the second column greater than 25
# create a Boolean mask where values in the 2nd column > 25 are True
condition = myarray[:,1] > 25
# Apply the mask
print('10. All values in 2nd column > 25: \n', myarray[condition])
print('\n')

# 11. Return values < 40 in the array
# create another Boolean mask for values < 40
condition = myarray < 40
# apply the mask
print('11. All values < 40: \n', myarray[condition])